FROM node:12.2.0-alpine

# set working directory
WORKDIR /app
# install and cache app dependencies
COPY package.json .
RUN npm install --silent
RUN npm install react-scripts@3.1.0 -g --silent
COPY . .

# start app
EXPOSE 3000
CMD ["npm", "start"]
